//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCvMiniProje.Models.entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbcvmvcEntities : DbContext
    {
        public dbcvmvcEntities()
            : base("name=dbcvmvcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_admin> tbl_admin { get; set; }
        public virtual DbSet<tbl_deneyimlerim> tbl_deneyimlerim { get; set; }
        public virtual DbSet<tbl_eğitim> tbl_eğitim { get; set; }
        public virtual DbSet<tbl_hakkımda> tbl_hakkımda { get; set; }
        public virtual DbSet<tbl_hobiler> tbl_hobiler { get; set; }
        public virtual DbSet<tbl_iletişim> tbl_iletişim { get; set; }
        public virtual DbSet<tbl_sertifikalar> tbl_sertifikalar { get; set; }
        public virtual DbSet<tbl_yetenekler> tbl_yetenekler { get; set; }
        public virtual DbSet<tbl_sosyalmedya> tbl_sosyalmedya { get; set; }
    }
}
