//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCvMiniProje.Models.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sertifikalar
    {
        public byte Id { get; set; }
        public string Açıklama { get; set; }
        public string Tarih { get; set; }
    }
}
